name: CI/CD with Self-Hosted Runner
on: workflow_dispatch
jobs:
  checkout:
    name: Checkout Code
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  build:
    name: Build & Push Docker Image
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ecomm:latest .
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecomm:latest
  deploy:
    name: Deploy App Container
    runs-on: self-hosted
    needs: build
    steps:
      - name: Stop & Remove Existing Container
        run: |
          docker stop my-app || true
          docker rm my-app || true
      - name: Run New Container
        run: |
          docker run -d --name my-app -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/ecomm:latest
